### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 01JDJ** [ellenmellon/GraphSum#2]
hello. An error was caught while executing the code, so I wrote the article.
In generate_graph_sum_input.py "corpus_type = sys.argv[1]" This part seems to mean the data path, but I keep getting an error at this part. I would be very grateful if you could explain this part. And you said to put the data file in parallel with src, but I do not understand this part, so I ask a question.

**Comment by ellenmellon** [comment]
Hi, thanks for your interest! If you go to the [run.sh](https://github.com/ellenmellon/GraphSum/blob/main/src/run.sh) file, you will notice that `corpus_type` means the data split name. Putting the data folder in parallel with the src folder means they should be under the same parent folder.

**Comment by 01JDJ** [comment]
<Exception: Model directory output does not exists !>

What should I do to resolve this error?

**Comment by 01JDJ** [comment]
Hello, I'm posting this because I couldn't proceed due to the pkl file. I made an 'uptut' file and put a pkl file in it, but the file size is too large to work. I'm curious about what kind of file the pkl file is.
`step_nb = int(file.split('/')[-1].split('.')[0]` keep getting an error in this part. I'm curious about how to do this part.

**Comment by ellenmellon** [comment]
Those are the model checkpoint files.

**Comment by 01JDJ** [comment]
Thanks for posting the answer.
